CREATE TABLE `clientes` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`email` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
	`nome` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
	`telefone` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
	`quarto` INT UNSIGNED NOT NULL,
	`pais` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
	`operador_id` INT UNSIGNED NOT NULL,
	PRIMARY KEY (`id`)
);
