CREATE TABLE `locais_frequentes` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`nome` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
	`zona` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
	`morada_gps` VARCHAR(250) CHARACTER SET 'utf8' NOT NULL,
	`morada` VARCHAR(250) CHARACTER SET 'utf8' NOT NULL,
	`referencias` VARCHAR(250) CHARACTER SET 'utf8' NOT NULL,
	PRIMARY KEY (`id`)
);